### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'findAll'

### ISSUE THREAD

**Issue by ghost** [NavjotBansal/PythonEdScClient#2]
This error pops up whenever I run the program 

> Traceback (most recent call last):
>   File "Script.py", line 112, in <module>
>     Notices(currentText,elements.text)
>   File "Script.py", line 16, in Notices
>     li = x.find('li',attrs={'aria-label':'Notice Section'}).findAll('div',attrs={'class':'activityinstance'})
> AttributeError: 'NoneType' object has no attribute 'findAll'
>

**Comment by NavjotBansal** [comment]
Change the details object to your ID and password sir

**Comment by ghost** [comment]
The content of folders in the announcement section is not downloaded.  Instead, there is a file called {name of folder} which redirects to the link of the folder

![screenshot from 2018-10-19 00-24-35](https://user-images.githubusercontent.com/28811003/47177199-62da4800-d335-11e8-8d0c-0e33cd7e7acb.png)

**Comment by navjotbans** [comment]
I will be having a look at them as soon as I reach the hostel 
Thanks for your feedback
